name: xcodebuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-on-mac:
    name: Build on macOS
    runs-on: [macos-12, macos-11, macos-10.15]
    steps:
      - uses: actions/checkout@v3
      - run: swift --version
      - run: xcodebuild -project ⌘英かな.xcodeproj -config Release
